apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-feature-flags
  namespace: demo
data:
  flags.yaml: |
    otel-nats-tracing:
      variations:
        enabled: true
        disabled: false
      defaultRule:
        variation: enabled
