{{- if and .Values.apiKeyAuth.enabled .Values.apiKeyAuth.vaultSecret.create }}
{{- $vaultSecret := .Values.apiKeyAuth.vaultSecret }}
apiVersion: {{ $vaultSecret.apiVersion }}
kind: {{ $vaultSecret.kind }}
metadata:
  name: {{ include "relay-proxy.apiKeySecretName" . }}
  labels:
    {{- include "relay-proxy.labels" . | nindent 4 }}
  {{- with $vaultSecret.annotations }}
  annotations:
    {{- include "relay-proxy.render" (dict "value" . "context" $) | nindent 4 }}
  {{- end }}
spec:
  path: {{ tpl $vaultSecret.path $ | quote }}
  type: {{ $vaultSecret.secretType }}
  {{- with $vaultSecret.keys }}
  keys:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $vaultSecret.extraSpec }}
  {{- include "relay-proxy.render" (dict "value" . "context" $) | nindent 2 }}
  {{- end }}
{{- end }}
